---
- name: Call hitotito.consul service tasks
  include_role:
    name: hitotito.consul
    tasks_from: service
    private: yes
  vars:
    consul_service_name: "{{ haproxy_consul_service_name }}"
    consul_service_tags: "{{ haproxy_consul_service_tags }}"
    consul_service_check: 'http'
    consul_service_ports: "{{ haproxy_consul_service_ports }}"

- name: Call hitotito.consul template tasks
  include_role:
    name: hitotito.consul
    tasks_from: template
    defaults_from: main
    private: yes
  vars:
    consul_service_template_name: "{{ haproxy_consul_service_name }}"
    consul_service_template_dest: "{{ haproxy_conf_dir }}/haproxy.cfg"
    consul_service_template_command: "systemctl reload-or-restart haproxy"
    consul_service_template_source_j2: "haproxy.ctmpl.j2"
