---
- name: Ensure HAProxy is installed
  apt:
    name: haproxy
    state: present

- name: Copy HAProxy configuration
  when: not haproxy_consul_enabled
  template:
    src: haproxy.cfg.j2
    dest: "{{ haproxy_conf_dir }}/haproxy.cfg"
    mode: 0644
  notify:
    - reload haproxy

- name: Ensure HAProxy sevice is enabled
  systemd:
    name: haproxy
    daemon_reload: true
    enabled: true
